### ISSUE TITLE
False positive - chatgpt.com

### ISSUE THREAD

**Issue by ikheetjeff** [r0xd4n3t/pihole-adblock-lists#1]
It seems that chatgpt.com is destroying the official chat.openai.com. So the domain is unfairly completely blocked. 

I read back [here ](https://domaininvesting.com/openai-secures-chatgpt-com/) that the domain was in the wrong hands at first.

But the domain now appears to be in use by OpenAI itself.

![afbeelding](https://github.com/r0xd4n3t/pihole-adblock-lists/assets/76551334/19929253-3699-4d15-92fd-9508fa95e6ad)

![afbeelding](https://github.com/r0xd4n3t/pihole-adblock-lists/assets/76551334/7a5266cb-0272-4da6-bdbb-d778b2da36c0)

**Comment by r0xd4n3t** [comment]
Hi @ikheetjeff,

Thank you for bringing this to our attention. We can confirm that chatgpt.com appears to be in use by OpenAI itself, and since the Domain Name Disputes at WIPO (https://www.wipo.int/amc/en/domains/search/case.jsp?case_id=63936) have been resolved with a decision of Termination, we understand the importance of ensuring its unblocking.

We will promptly initiate the process of removing chatgpt.com from the list in the upcoming version **1.3.3** of the Pihole Adlist.

If you have any additional information or insights that could assist us in addressing this issue more effectively, please feel free to share them. We appreciate your patience and understanding.

Best regards,
