### ISSUE TITLE
false positive - dumpert.nl

### ISSUE THREAD

**Issue by ikheetjeff** [r0xd4n3t/pihole-adblock-lists#2]
Hello,

I found out that dumpert.nl is completely blocked by your list. Based on other lists, I think this is because sexdumpert.nl also exists. 

![afbeelding](https://github.com/r0xd4n3t/pihole-adblock-lists/assets/76551334/f9515b7d-f2aa-4d6f-bae1-56e57cc07d58)

Dumpert.nl itself is a well-known website in the Netherlands. Funny internet videos are posted on this website. Dumpert is also an official company and has 2,7 million subscribers on Instagram. 

Dumpert also has a NFSW section/videos, so the fact that it's on a porn list is still justified. But on a general list is not quite justified, I think.

![afbeelding](https://github.com/r0xd4n3t/pihole-adblock-lists/assets/76551334/c22dd6d3-4206-4099-b856-9ad898395363)

https://nl.wikipedia.org/wiki/Dumpert
https://www.instagram.com/dumpert

I assume this is a false positive.

**Comment by r0xd4n3t** [comment]
Hi there,

Thank you for bringing this to our attention.
I've double-checked the **latest** [commit](https://github.com/r0xd4n3t/pihole-adblock-lists/commit/6c94c0e207915cc24c147a55f99fb70ae4ea6d80), and indeed Dumpert.nl is not included in the blocked list.

It's important to note that our list is automatically generated by combining data from various trusted sources like StevenBlack's hosts, PolishFiltersTeam KADhosts, FadeMind's hosts, and others.

However, false positives can occur due to the nature of automated processes.

We prioritize safety and accuracy in our blocklist, and if a website like Dumpert.nl is deemed safe, it will certainly be removed from the blocked list.

We understand the concern regarding its inclusion on a general block list.

Thank you for your contribution to this discussion, and please don't hesitate to reach out if you have any further questions or concerns.

**Comment by ikheetjeff** [comment]
Hi,

Thanks for your great work. I just noticed that dumpert.nl is back on the list, or it was never removed? This is clearly a false positive, especially for people in the Netherlands.

**Comment by r0xd4n3t** [comment]
Hi @ikheetjeff ,

Thank you for bringing this to our attention again.

We apologize for any inconvenience caused. It appears there may have been an oversight in our recent updates. We will review this matter thoroughly.

We are committed to ensuring our blocklist remains accurate and reliable. We will expedite the review process for `Dumpert.nl` to address this false positive. We will make sure that the domain is excluded in the next commit.

We love the Netherlands and value our users there.

Thank you for your patience and understanding. Please let us know if you encounter any further issues or have additional concerns.
