### ISSUE TITLE
false positive - stamps-app.com & stamps-app.nl

### ISSUE THREAD

**Issue by ikheetjeff** [r0xd4n3t/pihole-adblock-lists#3]
Hi,

Your malware list includes the domain “stamps-app.nl” and “stamps-app.com”. This seems, as far as I can see, unjustified.

These are domains of a (fairly young) dutch app. It is an app for sick people who can inform and update their loved ones in an easy way, and to which family can then respond.

Doesn't seem like malware to me. Or do you have other evidence? firebog.net also had it on their list, there I also submitted a false positive: maybe that's why it got on yours (or vice versa).

Thanks.

**Comment by r0xd4n3t** [comment]
> Hi,
> 
> Your malware list includes the domain “stamps-app.nl” and “stamps-app.com”. This seems, as far as I can see, unjustified.
> 
> These are domains of a (fairly young) dutch app. It is an app for sick people who can inform and update their loved ones in an easy way, and to which family can then respond.
> 
> Doesn't seem like malware to me. Or do you have other evidence? firebog.net also had it on their list, there I also submitted a false positive: maybe that's why it got on yours (or vice versa).
> 
> Thanks.


Hi @ikheetjeff ,

Thank you for bringing this to my attention. I understand your concern, and I apologize for any inconvenience. I'm currently busy, but I will make sure to verify the inclusion of "**stamps-app.nl**__" and "**stamps-app.com**__" in the malware list during my free time. If it turns out to be a false positive, I will make the necessary adjustments.

I appreciate your patience and will follow up with you once I've reviewed the situation.

Best regards,
@r0xd4n3t

**Comment by r0xd4n3t** [comment]
Hi @ikheetjeff ,

Thank you for your patience. I’ve reviewed your concern, and I agree that “stamps-app.nl” and “stamps-app.com” don’t seem to warrant inclusion in the malware list. This appears to be a false positive, possibly due to previous listings.

I've flagged this for correction, and these domains will be excluded in the upcoming release, version 1.3.6.

Thanks again for helping improve the accuracy of the list.

Best regards,
@r0xd4n3t
